/*
* generated by Xtext
*/
package spear.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class LanguageProposalProvider extends spear.ui.contentassist.AbstractLanguageProposalProvider {

}
