/*
 * generated by Xtext
 */
package com.rockwellcollins;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpearRuntimeModule extends com.rockwellcollins.AbstractSpearRuntimeModule {

}
