/*
 * generated by Xtext
 */
package com.rockwellcollins.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import com.rockwellcollins.ui.contentassist.SpearEObjectDocumentationProvider;
import com.rockwellcollins.ui.contentassist.SpearEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpearUiModule extends com.rockwellcollins.ui.AbstractSpearUiModule {
	public SpearUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return SpearEObjectHoverProvider.class;
    }
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
        return SpearEObjectDocumentationProvider.class;
		//return MultiLineCommentDocumentationProvider.class;
    }
}
