#!/bin/sh

usage="
$0:\n
$0 converts the ouput solution from the FaceLabelAssignment specification to\n
output where each line corresponds to a object label assignment. It reads\n
input through standard in.\n
"

 grep "^s\[" | sed -e "s/s\[//g" | sed -e "s/\]\[/ /g" | sed -e "s/\]\W*/ /g" | awk '{if(faces<$2){faces=$2;};if(objects<$1){objects=$1};a[$1, $2]=$3;}END{for(i = 0; i <= objects; i++){for(j = 0 ; j <= faces; j++){printf("%s ",a[i,j]);};printf("\n");}}'
exit 0;
