/*
* generated by Xtext
*/
package com.rockwellcollins;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SpearUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.rockwellcollins.ui.internal.SpearActivator.getInstance().getInjector("com.rockwellcollins.Spear");
	}
	
}
