/*
 * generated by Xtext
 */
package spear;
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends spear.AbstractLanguageRuntimeModule {
}
